### ISSUE TITLE
Repairing enhanced elytra will result in normal elytra

### ISSUE THREAD

**Issue by itsCryne** [Blaumeise03/ElytraArmour#2]
When you try to repair a pair of normal eltyras with a enhanced pair (or vice versa) in a crafting table you will get a normal pair of elytra back. If you try to repair them in an anvil it depends on the sequence. The anvil will return whichever type of elytra is lying in the first (left) slot

**Comment by itsCryne** [comment]
Furthermore I'm getting a NPE when combining a normal pair with an upgraded pair of Elytra in the workbench:
`[21:51:54 WARN]: java.lang.NullPointerException
[21:51:54 WARN]: 	at de.Blaumeise03.Plugins.ElytraArmour.CraftingListener.onCraft(CraftingListener.java:190)
[21:51:54 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor16.execute(Unknown Source)
[21:51:54 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:51:54 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:51:54 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:51:54 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1134)
[21:51:54 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[21:51:54 WARN]: 	at java.lang.Thread.run(Thread.java:748)
`
I am using 

> Paper version git-Paper-156 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Blaumeise03** [comment]
This is not a bug (the the Error itself is), because you can't repair an enchanted Item in the Workbench, this is Vanilla Minecraft

**Comment by Blaumeise03** [comment]
Solved

**Comment by itsCryne** [comment]
The elytras were **not** enchanted, one of the pairs was **enhanced** i.e. combined with a piece of armor
